package gnocchi

func SupportedResourceTypes() []ResourceType {
	return []ResourceType{
		MustResourceType("instance",
			ResourceTypeField{Name: "display_name", Type: "string"},
			ResourceTypeField{Name: "project_id", Type: "string"},
			ResourceTypeField{Name: "user_id", Type: "string"},
			ResourceTypeField{Name: "host", Type: "string"},
			ResourceTypeField{Name: "flavor_id", Type: "string"},
			ResourceTypeField{Name: "availability_zone", Type: "string"},
		),
		MustResourceType("volume",
			ResourceTypeField{Name: "name", Type: "string"},
			ResourceTypeField{Name: "project_id", Type: "string"},
			ResourceTypeField{Name: "user_id", Type: "string"},
			ResourceTypeField{Name: "status", Type: "string"},
			ResourceTypeField{Name: "server_id", Type: "string"},
			ResourceTypeField{Name: "volume_type", Type: "string"},
			ResourceTypeField{Name: "bootable", Type: "string"},
		),
		MustResourceType("network",
			ResourceTypeField{Name: "name", Type: "string"},
			ResourceTypeField{Name: "project_id", Type: "string"},
			ResourceTypeField{Name: "status", Type: "string"},
			ResourceTypeField{Name: "is_external", Type: "string"},
			ResourceTypeField{Name: "is_shared", Type: "string"},
			ResourceTypeField{Name: "provider_network_type", Type: "string"},
		),
		MustResourceType("port",
			ResourceTypeField{Name: "project_id", Type: "string"},
			ResourceTypeField{Name: "network_id", Type: "string"},
			ResourceTypeField{Name: "status", Type: "string"},
			ResourceTypeField{Name: "device_owner", Type: "string"},
			ResourceTypeField{Name: "fixed_ips", Type: "string"},
			ResourceTypeField{Name: "mac_address", Type: "string"},
		),
		MustResourceType("generic",
			ResourceTypeField{Name: "resource_type", Type: "string"},
			ResourceTypeField{Name: "project_id", Type: "string"},
		),
	}
}
