apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gnocchi-proxy-api.fullname" . }}-config
  labels:
    {{- include "gnocchi-proxy-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
